minimum_prek_version = "0.5.2"

[[repos]]
repo = "builtin"
hooks = [
    { id = "check-added-large-files", args = ["--maxkb=1000"] },
    { id = "check-merge-conflict" },
    { id = "check-toml" },
    { id = "check-yaml" },
    { id = "end-of-file-fixer" },
    { id = "trailing-whitespace" },
]

[[repos]]
repo = "local"

[[repos.hooks]]
id = "ruff-check"
name = "ruff check"
language = "system"
entry = "mise exec -- uv run --locked --no-sync ruff check --force-exclude"
args = ["--fix"]
types_or = ["python", "pyi"]

[[repos.hooks]]
id = "ruff-format"
name = "ruff format"
language = "system"
entry = "mise exec -- uv run --locked --no-sync ruff format --force-exclude"
types_or = ["python", "pyi"]
